export default new Model({
  applicant: '',
  applicantTime: '',
  approval: '',
  code: '',
  createTime: '',
  creator: '',
  id: '',
  ids: '',
  page: 1,
  receiver: '',
  receiverDepartment: '',
  remarks: '',
  size: 15,
  staut: 0,
  title: '',
  userId: '',
  uploadId: '',
  useDepartment: '',
  file: '',
  docId: '',
  assetsCategory: '',
  newCode: '',
  assetsName: ''
});
