export default new Model({
  id: '',
  ids: '',
  creator: '',
  createTime: '',
  remarks: '',
  roleCode: '',
  roleName: '',
  sortValue: '',
  updateTime: '',
  userId: '',
  page: '',
  size: '',
  modelId: '',
  roleId: '',
  bottenId: '',
  loginName: '',
  realName: '',
  departmentName: '',
  roleIds: '',
  departmentId: ''
});
