export default new Model({
  ids: '',
  applicant: '',
  applicantTime: '',
  code: '',
  id: '',
  page: 1,
  reasonForScrapping: '',
  remarks: '',
  scrappedTime: '',
  size: 15,
  title: '',
  userId: '',
  purchaseId: '',
  docId: '',
  uploadId: '',
  approvalType: '',
  file: '',
  time: '',
  staut: '',
  useDepartment: '',
  assetsCategory: '',
  newCode: '',
  assetsName: '',
  mark: '',
  acquisitionTime: '',
  useId: ''
});
