export default new Model({
  ids: '',
  userId: '',
  purchaseAssetsId: '',
  purchaseAssetsName: '',
  specification: '',
  amount: '',
  price: '',
  brand: '',
  unit: '',
  supplier: '',
  remarks: '',
  subtotal: '',
  acceptType: '',
  acceptor: '',
  acceptMethod: '',
  purchaseId: '',
  creator: '',
  page: 1,
  size: 10,
  id: ''
});
