export default new Model({
  id: '',
  ids: '',
  title: '',
  type: '',
  number: '',
  startTime: '',
  endTime: '',
  days: '',
  price: '',
  remarks: '',
  creator: '',
  createTime: '',
  acceptor: '',
  acceptMethod: '',
  acceptType: '',
  purchaseAssetsId: '',
  purchaseType: '',
  purchaseId: '',
  uploadId: '',
  docId: '',
  approvalType: '',
  file: '',
  time: '',
  page: 1,
  size: 10,
  mark: ''
});
